-- Создаем базу данных если не существует
SELECT 'CREATE DATABASE maindb'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'maindb')\gexec

-- Подключаемся к новой базе
\c maindb;

-- Создаем расширения если нужны
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Создаем таблицы или выполняем другие скрипты
-- CREATE TABLE IF NOT EXISTS tasks (...);

CREATE SEQUENCE IF NOT EXISTS public."tasks_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public."__EFMigrationsHistory" definition

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
	migration_id varchar(150) NOT NULL,
	product_version varchar(32) NOT NULL,
	CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


-- public.tasks definition

-- Drop table

-- DROP TABLE public.tasks;

CREATE TABLE IF NOT EXISTS public.tasks (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	title text NOT NULL,
	description text NOT NULL,
	due_date timestamptz NULL,
	status text NOT NULL DEFAULT 'New'::text,
	CONSTRAINT pk_tasks PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_tasks_due_date ON public.tasks USING btree (due_date);
CREATE INDEX IF NOT EXISTS ix_tasks_status ON public.tasks USING btree (status);

